
# https://www.youtube.com/watch?v=coO8XlhvmsU
###
# $ curl -X POST localhost:8080/api/employees -d "{\"firstName\": \"Bilbo\", \"lastName\": \"Baggins\", \"description\": \"burglar\"}" -H "Content-Type:application/json"
# {
#   "firstName" : "Bilbo",
#   "lastName" : "Baggins",
#   "description" : "burglar",
#   "_links" : {
#     "self" : {
#       "href" : "http://localhost:8080/api/employees/2"
#     }
#   }
# }

# curl --request POST http://localhost:8080/api/employees --data "{"firstName": "Bilbo", "lastName": "Baggins", "description": "burglar"}" --header "Content-Type:application/json"

# https://foreverframe.net/rest-client-great-vsc-extension-for-http-requests/
# https://josephwoodward.co.uk/2017/10/rest-%20client-for-vs-code-an-elegant-alternative-postman
# https://marketplace.visualstudio.com/items?itemName=humao.rest-client
# https://medium.com/@kilgarenone/you-might-not-need-postman-if-you-use-visual-studio-code-a77d9b9ec31

# POST /api/employees HTTP/1.1
# Host: localhost:8080
# Content-Type: application/json
POST http://localhost:8080/api/board HTTP/1.1
Content-Type: application/json

{
	"summary" : "Task 01",
	"acceptanceCriteria" : "create project board1"
}

###

POST http://localhost:8080/api/board HTTP/1.1
Content-Type: application/json

{
	"summary" : "Task 02",
	"acceptanceCriteria" : "create project board2"
}

###

###

POST http://localhost:8080/api/board HTTP/1.1
Content-Type: application/json

{
	"summary" : "Task 03",
	"acceptanceCriteria" : "create project board3"
}

###

POST http://localhost:8080/api/board HTTP/1.1
Content-Type: application/json

{
	"acceptanceCriteria" : "create project board"
}

###

GET http://localhost:8080/api/board/all HTTP/1.1

###

GET http://localhost:8080/api/board/2 HTTP/1.1























































GET http://localhost:8080/api HTTP/1.1
###
HTTP/1.1 200 
Content-Type: application/hal+json;charset=UTF-8
Transfer-Encoding: chunked
Date: Sun, 24 Mar 2019 04:39:09 GMT
Connection: close

{
  // the collection of links available.
  "_links": {
    // employees points to an aggregate root for the employee objects defined by the EmployeeRepository interface.
    "employees": {
      "href": "http://localhost:8080/api/employees"
    },
    // IANA-standard relation and points to discoverable metadata about the entire service.
    "profile": {
      "href": "http://localhost:8080/api/profile"
    }
  }
}

###
GET http://localhost:8080/api/employees HTTP/1.1
###
HTTP/1.1 200 
Content-Type: application/hal+json;charset=UTF-8
Transfer-Encoding: chunked
Date: Sun, 24 Mar 2019 06:23:47 GMT
Connection: close

{
  "_embedded": {
    "employees": [
      {
        "firstName": "Frodo",
        "lastName": "Baggins",
        "description": "ring bearer",
        "_links": {
          "self": {
            "href": "http://localhost:8080/api/employees/1"
          },
          "employee": {
            "href": "http://localhost:8080/api/employees/1"
          }
        }
      }
    ]
  },
  "_links": {
    "self": {
      "href": "http://localhost:8080/api/employees"
    },
    "profile": {
      "href": "http://localhost:8080/api/profile/employees"
    }
  }
}


###
GET http://localhost:8080/api/employees/1 HTTP/1.1
###
HTTP/1.1 200 
Content-Type: application/hal+json;charset=UTF-8
Transfer-Encoding: chunked
Date: Sun, 24 Mar 2019 06:25:24 GMT
Connection: close

{
  "firstName": "Frodo",
  "lastName": "Baggins",
  "description": "ring bearer",
  "_links": {
    "self": {
      "href": "http://localhost:8080/api/employees/1"
    },
    "employee": {
      "href": "http://localhost:8080/api/employees/1"
    }
  }
}
###
